name: minesweeper-server

services:
  gateway:
    build:
      context: ..
      dockerfile: build/Dockerfile.live
      target: gateway
    image: vancomm/mines-gateway:live
    container_name: mines-gateway
    ports:
      - "8080:8080"
    links:
      - db
      - game
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    volumes:
      - ../:/app
    environment:
      - APP_BASE_PATH=/api/v1
      - APP_PORT=:8080
      - DEVELOPMENT=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - COOKIES_DOMAIN=""
      - COOKIES_SECURE=""
      - COOKIES_SAMESITE=none
      - JWT_PRIVATE_KEY_FILE=/app/run/secrets/jwt-private-key.pem
      - JWT_PUBLIC_KEY_FILE=/app/run/secrets/jwt-public-key.pem

  game:
    build:
      context: ..
      dockerfile: build/Dockerfile.live
      target: game
    image: vancomm/mines-game:live
    container_name: mines-game
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    volumes:
      - ../:/app
    environment:
      - APP_PORT=:8080
      - DEVELOPMENT=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable

  migrator:
    build:
      context: ..
      dockerfile: build/Dockerfile
      target: migrator
    image: vancomm/mines-migrator:dev
    container_name: mines-migrator
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEVELOPMENT=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable

  db:
    image: postgres
    container_name: mines-db
    restart: unless-stopped
    healthcheck:
      test: [
          "CMD-SHELL",
          "psql -U $$POSTGRES_USER \
            -d $$POSTGRES_DB \
            -c 'select 1' || exit 1",
        ]
      interval: 3s
      timeout: 30s
      retries: 5
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR

volumes:
  db_data: