name: minesweeper-server

services:
  gateway:
    build:
      context: ..
      dockerfile: build/Dockerfile
      target: gateway
    image: vancomm/mines-gateway:dev
    container_name: mines-gateway
    ports:
      - "8080:8080"
    links:
      - db
      - game
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_MOUNT=/api/v1
      - APP_PORT=:8080
      - DEVELOPMENT=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - COOKIES_DOMAIN=""
      - COOKIES_SECURE=""
      - COOKIES_SAMESITE=none
      - JWT_PRIVATE_KEY_FILE=/run/secrets/jwt_private_key_file
      - JWT_PUBLIC_KEY_FILE=/run/secrets/jwt_public_key_file
    secrets:
      - jwt_private_key_file
      - jwt_public_key_file

  game:
    build:
      context: ..
      dockerfile: build/Dockerfile
      target: game
    image: vancomm/mines-game:dev
    container_name: mines-game
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_MOUNT=/game
      - APP_PORT=:8080
      - DEVELOPMENT=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
  
  db:
    image: postgres
    container_name: mines-db
    restart: unless-stopped
    healthcheck:
      test: [
          "CMD-SHELL", 
          "psql -U $$POSTGRES_USER \
            -d $$POSTGRES_DB \
            -c 'select 1' || exit 1",
        ]
      interval: 3s
      timeout: 30s
      retries: 5
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR

volumes:
  db_data:

# https://docs.docker.com/compose/how-tos/use-secrets/#use-secrets
# "Secrets are mounted as a file in /run/secrets/<secret_name> inside the
# container."
secrets:
  jwt_private_key_file:
    file: ../run/secrets/jwt-private-key.pem
  jwt_public_key_file:
    file: ../run/secrets/jwt-public-key.pem