name: minesweeper-server

services:
  server:
    build:
      context: ..
      dockerfile: build/Dockerfile.live
    image: vancomm/mines-server:live
    container_name: mines-server
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    volumes:
      - ../:/app
    environment:
      - APP_BASE_PATH=/api/v1
      - APP_PORT=:8080
      - DEVELOPMENT=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - COOKIES_DOMAIN=
      - COOKIES_SECURE=1
      - COOKIES_SAMESITE=strict
      - JWT_PRIVATE_KEY_FILE=/app/run/secrets/jwt-private-key.pem
      - JWT_PUBLIC_KEY_FILE=/app/run/secrets/jwt-public-key.pem

  db:
    image: postgres
    container_name: mines-db
    restart: unless-stopped
    healthcheck:
      test: [
          "CMD-SHELL",
          "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'select 1' || exit 1", 
      ]
      interval: 3s
      timeout: 30s
      retries: 5
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR

  migrator:
    build:
      context: ..
      dockerfile: build/Dockerfile
      target: migrator
    image: vancomm/mines-migrator:dev
    container_name: mines-migrator
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEVELOPMENT=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=5uL3KkJrlViMQoqR
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable


volumes:
  db_data: