services:
  db:
    image: postgres:17.4
    container_name: mines-db
    restart: unless-stopped
    healthcheck:
      test: [
          "CMD-SHELL",
          "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'select 1' || exit 1", 
      ]
      interval: 3s
      timeout: 30s
      retries: 5
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      
  server:
    build:
      context: ..
      dockerfile: build/Dockerfile
      target: server
    image: vancomm/mines-server:production
    container_name: mines-server
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    secrets:
      - postgres-password
      - jwt-private-key
      - jwt-public-key
    environment:
      - APP_MOUNT=/mines/v1
      - APP_PORT=:8080
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - COOKIES_DOMAIN=vancommdot.com
      - COOKIES_SECURE="1"
      - COOKIES_SAMESITE=strict
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - JWT_PRIVATE_KEY_FILE=/run/secrets/jwt-private-key
      - JWT_PUBLIC_KEY_FILE=/run/secrets/jwt-public-key
  
volumes:
  db_data:

secrets:
  postgres-password:
    external:
      true
  jwt-private-key:
    external:
      true
  jwt-public-key:
    external:
      true