# this config is meant to override docker-compose.yml
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: vancomm/mines-server:dev
    env_file: !override
      - "env/dev.env"
    volumes:
      - ./secrets:/app/secrets
  
  db:
    ports:
      - "54320:5432"
    env_file: !override
      - "env/dev.env"

  watchtower:
    deploy:
      replicas: 0