services:
  server:
    image: vancomm/mines-server:latest
    container_name: mines-server
    command: >
      sh -c "tern migrate --migrations migrations &&
            ./server -port 8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    links:
      - db
    env_file:
      - prod.env
  
  db:
    image: postgres:16.4@sha256:c62fdb7fd6f519ef425c54760894c74e8d0cb04fbf4f7d3d79aafd86bae24edd
    container_name: mines-db
    restart: always
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - prod.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -i 3600 mines-server

volumes:
  postgres-data: