services:
  server:
    build: .
    image: vancomm/mines-server:latest
    container_name: mines-server
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app/data
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data: