// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type GameSession struct {
	GameSessionID int64      `json:"game_session_id"`
	PlayerID      *int64     `json:"player_id"`
	Width         int32      `json:"width"`
	Height        int32      `json:"height"`
	MineCount     int32      `json:"mine_count"`
	Unique        bool       `json:"unique"`
	Dead          bool       `json:"dead"`
	Won           bool       `json:"won"`
	StartedAt     time.Time  `json:"started_at"`
	EndedAt       *time.Time `json:"ended_at"`
	State         []byte     `json:"-"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type Player struct {
	PlayerID     int64     `json:"player_id"`
	Username     string    `json:"username"`
	PasswordHash []byte    `json:"-"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
