// Code generated by "stringer -type=GameMove"; DO NOT EDIT.

package handlers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Open-1]
	_ = x[Flag-2]
	_ = x[Chord-3]
}

const _GameMove_name = "OpenFlagChord"

var _GameMove_index = [...]uint8{0, 4, 8, 13}

func (i GameMove) String() string {
	i -= 1
	if i >= GameMove(len(_GameMove_index)-1) {
		return "GameMove(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GameMove_name[_GameMove_index[i]:_GameMove_index[i+1]]
}
